
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilerminic;

import FlexAndCup.*;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUSEQUALS = 39;
  public static final int GREATERTHAN = 28;
  public static final int PLUSPLUS = 36;
  public static final int DIVIDE = 35;
  public static final int COMPARISSON = 25;
  public static final int CHAR = 10;
  public static final int DIVIDEEQUALS = 40;
  public static final int EQUALS = 24;
  public static final int LESSERTHAN = 26;
  public static final int INT = 8;
  public static final int FOR = 5;
  public static final int MINUS = 32;
  public static final int SEMICOLON = 42;
  public static final int NOT = 23;
  public static final int AND = 18;
  public static final int OR = 19;
  public static final int COMMA = 43;
  public static final int BOOL = 9;
  public static final int TIMESEQUALS = 41;
  public static final int NUM = 46;
  public static final int DIFFERENT = 30;
  public static final int PLUS = 31;
  public static final int QUOTE = 11;
  public static final int IF = 2;
  public static final int ID = 45;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 37;
  public static final int GREATEREQUALTHAN = 29;
  public static final int RETURN = 6;
  public static final int TRUE = 20;
  public static final int error = 1;
  public static final int NULL = 22;
  public static final int OPEN_BRACE = 16;
  public static final int MOD = 34;
  public static final int CLOSE_BRACKET = 15;
  public static final int BREAK = 7;
  public static final int OPEN_BRACKET = 14;
  public static final int OPEN_PARENTHESIS = 12;
  public static final int TIMES = 33;
  public static final int LESSEREQUALTHAN = 27;
  public static final int ELSE = 3;
  public static final int WHILE = 4;
  public static final int STRING = 47;
  public static final int QUESTION = 44;
  public static final int CLOSE_PARENTHESIS = 13;
  public static final int CLOSE_BRACE = 17;
  public static final int FALSE = 21;
  public static final int PLUSEQUALS = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "RETURN",
  "BREAK",
  "INT",
  "BOOL",
  "CHAR",
  "QUOTE",
  "OPEN_PARENTHESIS",
  "CLOSE_PARENTHESIS",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "OPEN_BRACE",
  "CLOSE_BRACE",
  "AND",
  "OR",
  "TRUE",
  "FALSE",
  "NULL",
  "NOT",
  "EQUALS",
  "COMPARISSON",
  "LESSERTHAN",
  "LESSEREQUALTHAN",
  "GREATERTHAN",
  "GREATEREQUALTHAN",
  "DIFFERENT",
  "PLUS",
  "MINUS",
  "TIMES",
  "MOD",
  "DIVIDE",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUSEQUALS",
  "MINUSEQUALS",
  "DIVIDEEQUALS",
  "TIMESEQUALS",
  "SEMICOLON",
  "COMMA",
  "QUESTION",
  "ID",
  "NUM",
  "STRING"
  };
}

