package FlexAndCup;

import java_cup.runtime.Symbol;

parser code
{:
    private Symbol s;

    public void syntax_error(Symbol s){
        this.s = s
    }


    public Symbol getS(){
        return this.s;
    }

:};

//Terminals
terminal IF, ELSE, WHILE, FOR, RETURN;
terminal INT, STRING;
terminal OPEN_PARENTHESIS, CLOSE_PARENTHESIS, OPEN_BRACKET, CLOSE_BRACKET, OPEN_BRACE, CLOSE_BRACE;
terminal AND, OR, TRUE, FALSE, NULL

//Non terminals