package proyectocompiladores;

import proyectocompiladores.TreeNode;
import java.io.*;
import java_cup.runtime.*;
import java.util.ArrayList;


parser code {:
    ArrayList<String> errors = new ArrayList();
    
    public parser (java.io.Reader input) {super(new Lexer(input));}
	public void report_error(String errorBody, Object info) {
		StringBuffer errorHead = new StringBuffer("Error");
			if(info instanceof java_cup.runtime.Symbol){
                            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
                            if (s.left >= 0) {
                                errorHead.append(" en la linea "+(s.right+1));
                                if (s.right >= 0){
                                    errorHead.append(", columna "+(s.left+1));
                                }
			}
			if(s.value != null){
                            errorHead.append(" en el token "+s.value );
							//System.out.println("veamos que hay aqui ");
							//System.out.println(s.value +" ");
                                                        if(s.value == "#-1"){
                                                            return;
                                                        }
							errorHead.append(": "+ getToken(Integer.parseInt(s.value.toString().replaceAll("#",""))));
							
			}
			errorHead.append(": ");
                       // errorHead.append(": " + getToken((int) s.value));

                        
		}
		System.err.print(errorHead);
                errors.add(errorHead +" ");
	}

        public String getToken(int id){
            String value = "";
            value = sym.terminalNames[id];
            return value;
        }
           
:};

terminal IDENTIFIER, CONSTANT, STRING_LITERAL, SIZEOF, PTR_OP, INC_OP, DEC_OP, LEFT_OP, RIGHT_OP, LE_OP, GE_OP, EQ_OP, NE_OP,
		AND_OP, OR_OP, MUL_ASSIGN, DIV_ASSIGN, MOD_ASSIGN, ADD_ASSIGN, SUB_ASSIGN, LEFT_ASSIGN, RIGHT_ASSIGN, AND_ASSIGN,
		XOR_ASSIGN, OR_ASSIGN, TYPE_NAME, TYPEDEF, EXTERN, STATIC, AUTO, REGISTER,
		CHAR, SHORT, INT, LONG, SIGNED, UNSIGNED, FLOAT, DOUBLE, CONST, VOLATILE, VOID, STRUCT, UNION, ENUM, ELLIPSIS,
		CASE, DEFAULT, IF, ELSE, SWITCH, WHILE, DO, FOR, GOTO, CONTINUE, BREAK, RETURN,
		SEMI, CURLYL, CURLYR, COMMA, COLON, ASSIGN, PARAL, PARAR, SQUAREDL, SQUAREDR, POINT, ADRESS,
		NOT, TILDE, MINUS, PLUS, MUL, DIVIDE, MODULUS, LESS, GREATER, XOR, OR, COND,
		SCANF, PRINTF;

non terminal TreeNode translation_unit;
non terminal TreeNode primary_expression;
non terminal TreeNode postfix_expression;
non terminal TreeNode expression;
non terminal TreeNode assignment_expression;
non terminal TreeNode unary_expression;
non terminal TreeNode unary_operator;
non terminal TreeNode type_name;
non terminal TreeNode cast_expression;
non terminal TreeNode multiplicative_expression;
non terminal TreeNode additive_expression;
non terminal TreeNode relational_expression;
non terminal TreeNode shift_expression;
non terminal TreeNode equality_expression;
non terminal TreeNode and_expression;
non terminal TreeNode exclusive_or_expression;
non terminal TreeNode inclusive_or_expression;
non terminal TreeNode logical_and_expression;
non terminal TreeNode logical_or_expression;
non terminal TreeNode conditional_expression;
non terminal TreeNode constant_expression;
non terminal TreeNode declaration;
non terminal TreeNode declaration_specifiers;
non terminal TreeNode init_declarator_list;
non terminal TreeNode storage_class_specifier;
non terminal TreeNode type_specifier;
non terminal TreeNode type_qualifier;
non terminal TreeNode init_declarator;
non terminal TreeNode declarator;
non terminal TreeNode struct_or_union_specifier;
non terminal TreeNode struct_declaration_list;
non terminal TreeNode struct_declaration;
non terminal TreeNode initializer;
non terminal TreeNode specifier_qualifier_list;
non terminal TreeNode struct_declarator_list;
non terminal TreeNode struct_declarator;
non terminal TreeNode enum_specifier;
non terminal TreeNode enumerator_list;
non terminal TreeNode enumerator;
non terminal TreeNode pointer;
non terminal TreeNode direct_declarator;
non terminal TreeNode parameter_type_list;
non terminal TreeNode identifier_list;
non terminal TreeNode type_qualifier_list;
non terminal TreeNode parameter_declaration;
non terminal TreeNode abstract_declarator;
non terminal TreeNode direct_abstract_declarator;
non terminal TreeNode initializer_list;
non terminal TreeNode statement;
non terminal TreeNode labeled_statement;
non terminal TreeNode compound_statement;
non terminal TreeNode selection_statement;
non terminal TreeNode iteration_statement;
non terminal TreeNode jump_statement;
non terminal TreeNode expression_statement;
non terminal TreeNode external_declaration;
non terminal TreeNode function_definition;
non terminal TreeNode declaration_list;
non terminal TreeNode statement_list;
non terminal TreeNode decl_stmnt_list;
non terminal TreeNode assignment_operator;
non terminal TreeNode parameter_list;

precedence nonassoc ELSE;
start with translation_unit;

primary_expression ::=
	IDENTIFIER:ident {:
		System.err.println("Produccion 1");
		TreeNode parent = new TreeNode(null, "primary_expression");
		parent.addChild(ident);
		RESULT = parent;
		
	:}
	| CONSTANT:constant {:
		System.err.println("Produccion 2");
		TreeNode parent = new TreeNode(null, "primary_expression");
		parent.addChild(constant);
		RESULT = parent;
		

	:}
	| STRING_LITERAL:stringliteral {:
		System.err.println("Produccion 3");
		TreeNode parent = new TreeNode(null, "primary_expression");
		parent.addChild(stringliteral);
		RESULT = parent;
		
	:}
	| PARAL:pl expression:e PARAR:pr {:
		System.err.println("Produccion 4");
		TreeNode parent = new TreeNode(null, "primary_expression");
		parent.addChild(e);
		RESULT = parent;
	:}
	;

postfix_expression ::=
	primary_expression:pe {:
		System.err.println("Produccion 5");
		TreeNode parent = new TreeNode(null, "postfix_expression");
		parent.addChild(pe);
		RESULT = parent;
	:}
	| postfix_expression:pe SQUAREDL:sl expression:index SQUAREDR:sd {:
		System.err.println("Produccion 6");
		TreeNode parent = new TreeNode(null, "postfix_expression");
		parent.addChild(new Symbol(-1,0,0,"array"));
		parent.addChild(pe);
		parent.addChild(index);
		RESULT = parent;
	:}
	| postfix_expression:pe PARAL:pl PARAR:pr {:
		System.err.println("Produccion 7");
		TreeNode parent = new TreeNode(null, "postfix_expression");
		parent.addChild(new Symbol(-1,0,0,"function_call"));
		parent.addChild(pe);
		RESULT = parent;
	:}
	| postfix_expression:pe PARAL:pl expression:e PARAR:pr {:
		System.err.println("Produccion 8");
		TreeNode parent = new TreeNode(null, "postfix_expression");
		parent.addChild(new Symbol(-1,0,0,"function_call"));
		parent.addChild(pe);
		parent.addChild(e);
		RESULT = parent;
	:}
	| PRINTF:pf PARAL:pl PARAR:pr {:
		System.err.println("Produccion 9");
		TreeNode parent = new TreeNode(null, "postfix_expression");
		parent.addChild(new Symbol(-1,0,0,"function_call"));
		parent.addChild(pf);
		RESULT = parent;
	:}
	| SCANF:sf PARAL:pl PARAR:pr {:
		System.err.println("Produccion 10");
		TreeNode parent = new TreeNode(null, "postfix_expression");
		parent.addChild(new Symbol(-1,0,0,"function_call"));
		parent.addChild(sf);
		RESULT = parent;
	:}
	| PRINTF:pf PARAL:pl expression:e PARAR:pr {:
		System.err.println("Produccion 11");
		TreeNode parent = new TreeNode(null, "postfix_expression");
		parent.addChild(new Symbol(-1,0,0,"function_call"));
		parent.addChild(pf);
		parent.addChild(e);
		RESULT = parent;
	:}
	| SCANF:sf PARAL:pl expression:e PARAR:pr {:
		System.err.println("Produccion 12");
		TreeNode parent = new TreeNode(null, "postfix_expression");
		parent.addChild(new Symbol(-1,0,0,"function_call"));
		parent.addChild(sf);
		parent.addChild(e);
		RESULT = parent;
	:}
	| postfix_expression:pe POINT:p IDENTIFIER:id {:
		System.err.println("Produccion 13");
		TreeNode parent = new TreeNode(null, "postfix_expression");
		parent.addChild(pe);
		parent.addChild(p);
		parent.addChild(id);
		RESULT = parent;
	:}
	| postfix_expression:pe PTR_OP:po IDENTIFIER:id {:
		System.err.println("Produccion 14");
		TreeNode parent = new TreeNode(null, "postfix_expression");
		parent.addChild(pe);
		parent.addChild(po);
		parent.addChild(id);
		RESULT = parent;
	:}
	| postfix_expression:pe INC_OP:op {:
		System.err.println("Produccion 15");
		TreeNode parent = new TreeNode(null, "postfix_expression");
		parent.addChild(pe);
		parent.addChild(op);
		RESULT = parent;
	:}
	| postfix_expression:pe DEC_OP:op {:
		System.err.println("Produccion 16");
		TreeNode parent = new TreeNode(null, "postfix_expression");
		parent.addChild(pe);
		parent.addChild(op);
		RESULT = parent;
	:}
	;

unary_expression ::=
	postfix_expression:pe {:
		System.err.println("Produccion 17");
		TreeNode parent = new TreeNode(null, "unary_expression");
		parent.addChild(pe);
		RESULT = parent;
	:}
	| INC_OP:op unary_expression:ue {:
		System.err.println("Produccion 18");
		TreeNode parent = new TreeNode(null, "unary_expression");
		parent.addChild(op);
		parent.addChild(ue);
		RESULT = parent;
	:}
	| DEC_OP:op unary_expression:ue {:
		System.err.println("Produccion 19");
		TreeNode parent = new TreeNode(null, "unary_expression");
		parent.addChild(op);
		parent.addChild(ue);
		RESULT = parent;
	:}
	| unary_operator:uo cast_expression:ce {:
		System.err.println("Produccion 20");

		TreeNode parent = new TreeNode(null, "unary_expression");
		parent.addChild(uo);
		parent.addChild(ce);
		RESULT = parent;
	:}
	| SIZEOF:so unary_expression:ue {:
		System.err.println("Produccion 21");

		TreeNode parent = new TreeNode(null, "unary_expression");
		parent.addChild(so);
		parent.addChild(ue);
		RESULT = parent;
	:}
	| SIZEOF:so PARAL type_name:tn PARAR {:
		System.err.println("Produccion 22");
		TreeNode parent = new TreeNode(null, "unary_expression");
		parent.addChild(so);
		parent.addChild(tn);
		RESULT = parent;
	:}
	;

unary_operator ::=
	ADRESS:op {:
		System.err.println("Produccion 23");
		TreeNode parent = new TreeNode(null, "unary_operator");
		parent.addChild(op);
		RESULT = parent;
	:}
	| MUL:op {:
		System.err.println("Produccion 24");
		TreeNode parent = new TreeNode(null, "unary_operator");
		parent.addChild(op);
		RESULT = parent;
	:}
	| PLUS:op {:
		System.err.println("Produccion 25");
		TreeNode parent = new TreeNode(null, "unary_operator");
		parent.addChild(op);
		RESULT = parent;
	:}
	| MINUS:op {:
		System.err.println("Produccion 26");
		TreeNode parent = new TreeNode(null, "unary_operator");
		parent.addChild(op);
		RESULT = parent;
	:}
	| TILDE:op {:
		System.err.println("Produccion 27");
		TreeNode parent = new TreeNode(null, "unary_operator");
		parent.addChild(op);
		RESULT = parent;
	:}
	| NOT:op {:
		System.err.println("Produccion 28");
		TreeNode parent = new TreeNode(null, "unary_operator");
		parent.addChild(op);
		RESULT = parent;
	:}
	;


cast_expression ::=
	unary_expression:ue {:
		System.err.println("Produccion 29");
		TreeNode parent = new TreeNode(null, "cast_expression");
		parent.addChild(ue);
		RESULT = parent;
	:}
	| PARAL type_name:tn PARAR cast_expression:ce {:
		System.err.println("Produccion 30");
		TreeNode parent = new TreeNode(null, "cast_expression");
		parent.addChild(tn);
		parent.addChild(ce);
		RESULT = parent;
	:}
	;


multiplicative_expression ::=
	cast_expression:ce {:
		System.err.println("Produccion 31");
		TreeNode parent = new TreeNode(null, "multiplicative_expression");
		parent.addChild(ce);
		RESULT = parent;
	:}
	| multiplicative_expression:me MUL:op cast_expression:ce {:
		System.err.println("Produccion 32");
		TreeNode parent = new TreeNode(null, "multiplicative_expression");
		TreeNode child = new TreeNode(parent, (Symbol)op);
		parent.addChild(child);
		child.addChild(me);
		child.addChild(ce);
		RESULT = parent;
	:}
	| multiplicative_expression:me DIVIDE:op cast_expression:ce {:
		System.err.println("Produccion 33");
		TreeNode parent = new TreeNode(null, "multiplicative_expression");
		TreeNode child = new TreeNode(parent, (Symbol)op);
		parent.addChild(child);
		child.addChild(me);
		child.addChild(ce);
		RESULT = parent;
	:}
	| multiplicative_expression:me MODULUS:op cast_expression:ce {:
		System.err.println("Produccion 34");
		TreeNode parent = new TreeNode(null, "multiplicative_expression");
		TreeNode child = new TreeNode(parent, (Symbol)op);
		parent.addChild(child);
		child.addChild(me);
		child.addChild(ce);
		RESULT = parent;
	:}
	;

additive_expression ::=
	multiplicative_expression:me {:
		System.err.println("Produccion 35");
		TreeNode parent = new TreeNode(null, "additive_expression");
		parent.addChild(me);
		RESULT = parent;
	:}
	| additive_expression:ae PLUS:op multiplicative_expression:me {:
                System.err.println("Produccion 35.5");
		TreeNode parent = new TreeNode(null, "additive_expression");
		TreeNode child = new TreeNode(parent, (Symbol)op);
		parent.addChild(child);
		child.addChild(ae);
		child.addChild(me);
		RESULT = parent;
	:}
	| additive_expression:ae MINUS:op multiplicative_expression:me {:
		System.err.println("Produccion 36");
		TreeNode parent = new TreeNode(null, "additive_expression");
		TreeNode child = new TreeNode(parent, (Symbol)op);
		parent.addChild(child);
		child.addChild(ae);
		child.addChild(me);
		RESULT = parent;
	:}
	;

shift_expression ::=
	additive_expression:ae {:
		System.err.println("Produccion 37");
		TreeNode parent = new TreeNode(null, "shift_expression");
		parent.addChild(ae);
		RESULT = parent;
	:}
	| shift_expression:se LEFT_OP:op additive_expression:ae {:
		System.err.println("Produccion 38");
		TreeNode parent = new TreeNode(null, "shift_expression");
		TreeNode child = new TreeNode(parent, (Symbol)op);
		parent.addChild(child);
		child.addChild(se);
		child.addChild(ae);
		RESULT = parent;
	:}
	| shift_expression:se RIGHT_OP:op additive_expression:ae {:
		System.err.println("Produccion 39");
		TreeNode parent = new TreeNode(null, "shift_expression");
		TreeNode child = new TreeNode(parent, (Symbol)op);
		parent.addChild(child);
		parent.addChild(se);
		parent.addChild(ae);
		RESULT = parent;
	:}
	;

relational_expression ::=
	shift_expression:se {:
		System.err.println("Produccion 40");
		TreeNode parent = new TreeNode(null, "relational_expression");
		parent.addChild(se);
		RESULT = parent;
	:}
	| relational_expression:re LESS:op shift_expression:se {:
		System.err.println("Produccion 41");
		TreeNode parent = new TreeNode(null, "relational_expression");
		parent.addChild(re);
		parent.addChild(op);
		parent.addChild(se);
		RESULT = parent;
	:}
	| relational_expression:re GREATER:op shift_expression:se {:
		System.err.println("Produccion 42");
		TreeNode parent = new TreeNode(null, "relational_expression");
		parent.addChild(re);
		parent.addChild(op);
		parent.addChild(se);
		RESULT = parent;
	:}
	| relational_expression:re LE_OP:op shift_expression:se {:
		System.err.println("Produccion 43");
		TreeNode parent = new TreeNode(null, "relational_expression");
		parent.addChild(re);
		parent.addChild(op);
		parent.addChild(se);
		RESULT = parent;
	:}
	| relational_expression:re GE_OP:op shift_expression:se {:
		System.err.println("Produccion 44");
		TreeNode parent = new TreeNode(null, "relational_expression");
		parent.addChild(re);
		parent.addChild(op);
		parent.addChild(se);
		RESULT = parent;
	:}
	;

equality_expression ::=
	relational_expression:re {:
		System.err.println("Produccion 45");
		TreeNode parent = new TreeNode(null, "equality_expression");
		parent.addChild(re);
		RESULT = parent;
	:}
	| equality_expression:ee EQ_OP:op relational_expression:re {:
		System.err.println("Produccion 46");
		TreeNode parent = new TreeNode(null, "equality_expression");
		parent.addChild(ee);
		parent.addChild(op);
		parent.addChild(re);
		RESULT = parent;
	:}
	| equality_expression:ee NE_OP:op relational_expression:re {:
		System.err.println("Produccion 47");
		TreeNode parent = new TreeNode(null, "equality_expression");
		parent.addChild(ee);
		parent.addChild(op);
		parent.addChild(re);
		RESULT = parent;
	:}
	;

and_expression ::=
	equality_expression:ee {:
		System.err.println("Produccion 48");
		TreeNode parent = new TreeNode(null, "and_expression");
		parent.addChild(ee);
		RESULT = parent;
	:}
	| and_expression:ae ADRESS:a equality_expression:ee {:
		System.err.println("Produccion 49");
		TreeNode parent = new TreeNode(null, "and_expression");
		parent.addChild(ae);
		parent.addChild(ee);
		RESULT = parent;
	:}
	;

exclusive_or_expression	::=
	and_expression:ae {:
		System.err.println("Produccion 50");
		TreeNode parent = new TreeNode(null, "and_expression");
		parent.addChild(ae);
		RESULT = parent;
	:}
	| exclusive_or_expression:eoe XOR and_expression:ae {:
		System.err.println("Produccion 51");
		TreeNode parent = new TreeNode(null, "and_expression");
		parent.addChild(eoe);
		parent.addChild(ae);
		RESULT = parent;
	:}
	;


inclusive_or_expression	::=
	exclusive_or_expression:eoe {:
		System.err.println("Produccion 52");
		TreeNode parent = new TreeNode(null, "inclusive_or_expression");
		parent.addChild(eoe);
		RESULT = parent;
	:}
	| inclusive_or_expression:ioe OR exclusive_or_expression:eoe {:
                System.err.println("Produccion 52.5");
		TreeNode parent = new TreeNode(null, "inclusive_or_expression");
		parent.addChild(ioe);
		parent.addChild(eoe);
		RESULT = parent;
	:}
	;

logical_and_expression ::=
	inclusive_or_expression:ioe {:
		System.err.println("Produccion 53");
		TreeNode parent = new TreeNode(null, "logical_and_expression");
		parent.addChild(ioe);
		RESULT = parent;
	:}
	| logical_and_expression:lae AND_OP:op inclusive_or_expression:ioe {:
		System.err.println("Produccion 54");
		TreeNode parent = new TreeNode(null, "logical_and_expression");
		parent.addChild(lae);
		parent.addChild(ioe);
		RESULT = parent;
	:}
	;

logical_or_expression ::=
	logical_and_expression:lae {:
		System.err.println("Produccion 55");
		TreeNode parent = new TreeNode(null, "logical_or_expression");
		parent.addChild(lae);
		RESULT = parent;
	:}
	| logical_or_expression:loe OR_OP:op logical_and_expression:lae {:
		System.err.println("Produccion 56");
		TreeNode parent = new TreeNode(null, "logical_or_expression");
		parent.addChild(loe);
		parent.addChild(lae);
		RESULT = parent;
	:}
	;

conditional_expression ::=
	logical_or_expression:loe {:
		System.err.println("Produccion 57");
		TreeNode parent = new TreeNode(null, "conditional_expression");
		parent.addChild(loe);
		RESULT = parent;
	:}
	| logical_or_expression:loe COND expression:e COLON conditional_expression:ce {:
		System.err.println("Produccion 58");
		TreeNode parent = new TreeNode(null, "conditional_expression");
		parent.addChild(loe);
		parent.addChild(e);
		parent.addChild(ce);
		RESULT = parent;
	:}
	;

assignment_expression ::=
	conditional_expression:ce {:
		System.err.println("Produccion 59");
		TreeNode parent = new TreeNode(null, "assignment_expression");
		parent.addChild(ce);
		RESULT = parent;
	:}
	| unary_expression:ue assignment_operator:aop assignment_expression:ae {:
		System.err.println("Produccion 60");
		TreeNode parent = new TreeNode(null, "assignment_expression");
		TreeNode child = new TreeNode(null, aop.getValue());
		parent.addChild(child);
		child.addChild(ue);
		child.addChild(ae);
		RESULT = parent;
	:}
	| error assignment_operator:aop assignment_expression:ae {:
		System.err.println("Produccion 61");
		TreeNode parent = new TreeNode(null, "assignment_expression");
		TreeNode child = new TreeNode(parent, aop.getValue());
		parent.addChild(child);
		child.addChild(new Symbol(-1,0,0,"ERROR"));
		child.addChild(ae);
		RESULT = parent;
		System.err.println("Asignacion solo a identificadores");
		this.parser.errors.add("Asignacion solo a identificadores");

		//System.err.println(RESULT);
	:}
	;

assignment_operator ::=
	ASSIGN:a {:
		System.err.println("Produccion 62");
		TreeNode parent = new TreeNode(null, (Symbol)a);
		RESULT = parent;
	:}
	| MUL_ASSIGN:a {:
		System.err.println("Produccion 63");
		TreeNode parent = new TreeNode(null, (Symbol)a);
		RESULT = parent;
	:}
	| DIV_ASSIGN:a {:
		System.err.println("Produccion 64");
		TreeNode parent = new TreeNode(null, (Symbol)a);
		RESULT = parent;
	:}
	| MOD_ASSIGN:a {:
		System.err.println("Produccion 65");
		TreeNode parent = new TreeNode(null, (Symbol)a);
		RESULT = parent;
	:}
	| ADD_ASSIGN:a {:
		System.err.println("Produccion 66");
		TreeNode parent = new TreeNode(null, (Symbol)a);
		RESULT = parent;
	:}
	| SUB_ASSIGN:a {:
		System.err.println("Produccion 67");
		TreeNode parent = new TreeNode(null, (Symbol)a);
		RESULT = parent;
	:}
	| LEFT_ASSIGN:a {:
		System.err.println("Produccion 68");
		TreeNode parent = new TreeNode(null, (Symbol)a);
		RESULT = parent;
	:}
	| RIGHT_ASSIGN:a {:
		System.err.println("Produccion 69");
		TreeNode parent = new TreeNode(null, (Symbol)a);
		RESULT = parent;
	:}
	| AND_ASSIGN:a {:
		System.err.println("Produccion 70");
		TreeNode parent = new TreeNode(null, (Symbol)a);
		RESULT = parent;
	:}
	| XOR_ASSIGN:a {:
		System.err.println("Produccion 71");
		TreeNode parent = new TreeNode(null, (Symbol)a);
		RESULT = parent;
	:}
	| OR_ASSIGN:a {:
		System.err.println("Produccion 72");
		TreeNode parent = new TreeNode(null, (Symbol)a);
		RESULT = parent;
	:}
	;

expression ::=
	assignment_expression:ae {:
		System.err.println("Produccion 73");
		TreeNode parent = new TreeNode(null, "expression");
		parent.addChild(ae);
		RESULT = parent;
	:}
	| expression:e COMMA assignment_expression:ae {:
		System.err.println("Produccion 74");
		TreeNode parent = new TreeNode(null, "expression");
		parent.addChild(e);
		parent.addChild(ae);
		RESULT = parent;
	:}
	;

constant_expression ::=
	conditional_expression:ce {:
		System.err.println("Produccion 75");
		TreeNode parent = new TreeNode(null, "constant_expression");
		parent.addChild(ce);
		RESULT = parent;
	:}
	;

declaration ::=
	declaration_specifiers:ds SEMI {:
		System.err.println("Produccion 76");
		TreeNode parent = new TreeNode(null, "declaration");
		parent.addChild(ds);
		RESULT = parent;
	:}
	| declaration_specifiers:ds init_declarator_list:idl SEMI {:
		System.err.println("Produccion 77");
		TreeNode parent = new TreeNode(null, "declaration");
		parent.addChild(ds);
		parent.addChild(idl);
		RESULT = parent;
	:}
	| declaration_specifiers:ds error {:
		System.err.println("Produccion 78");
		TreeNode parent = new TreeNode(null, "declaration");
		parent.addChild(ds);
		parent.addChild(new Symbol(-1,0,0,"ERROR"));
		RESULT = parent;
		System.err.println("Se esperaba ; en la declaracion:");
		this.parser.errors.add("Se esperaba ; en la declaracion:");

		//System.err.println(RESULT);
	:}
	;

declaration_specifiers ::=
	storage_class_specifier:scc {:
		System.err.println("Produccion 79");
		TreeNode parent = new TreeNode(null, "declaration_specifiers");
		parent.addChild(scc);
		RESULT = parent;
	:}
	| storage_class_specifier:scc declaration_specifiers:ds {:
		System.err.println("Produccion 80");
		TreeNode parent = new TreeNode(null, "declaration_specifiers");
		parent.addChild(scc);
		parent.addChild(ds);
		RESULT = parent;
	:}
	| type_specifier:ts {:
		System.err.println("Produccion 81");
		TreeNode parent = new TreeNode(null, "declaration_specifiers");
		parent.addChild(ts);
		RESULT = parent;
	:}
	| type_specifier:ts declaration_specifiers:ds {:
		System.err.println("Produccion 82");
		TreeNode parent = new TreeNode(null, "declaration_specifiers");
		parent.addChild(ts);
		parent.addChild(ds);
		RESULT = parent;
	:}
	| type_qualifier:tq {:
		System.err.println("Produccion 83");
		TreeNode parent = new TreeNode(null, "declaration_specifiers");
		parent.addChild(tq);
		RESULT = parent;
	:}
	| type_qualifier:tq declaration_specifiers:ds {:
		System.err.println("Produccion 84");
		TreeNode parent = new TreeNode(null, "declaration_specifiers");
		parent.addChild(tq);
		parent.addChild(ds);
		RESULT = parent;
	:}
	;

init_declarator_list ::=
	init_declarator:id {:
		System.err.println("Produccion 85");
		TreeNode parent = new TreeNode(null, "init_declarator_list");
		parent.addChild(id);
		RESULT = parent;
	:}
	| init_declarator_list:idl COMMA init_declarator:id {:
		System.err.println("Produccion 86");
		TreeNode parent = new TreeNode(null, "init_declarator_list");
		parent.addChild(idl);
		parent.addChild(id);
		RESULT = parent;
	:}
	;

init_declarator ::=
	declarator:d {:
		System.err.println("Produccion 87");
		TreeNode parent = new TreeNode(null, "init_declarator");
		parent.addChild(d);
		RESULT = parent;
	:}
	| declarator:d ASSIGN initializer:i {:
		System.err.println("Produccion 88");
		TreeNode parent = new TreeNode(null, "init_declarator");
		parent.addChild(d);
		parent.addChild(i);
		RESULT = parent;
	:}
	;

storage_class_specifier ::=
	TYPEDEF:id {:
		System.err.println("Produccion 89");
		TreeNode parent = new TreeNode(null, "storage_class_specifier");
		parent.addChild(id);
		RESULT = parent;
	:}
	| EXTERN:id {:
		System.err.println("Produccion 90");
		TreeNode parent = new TreeNode(null, "storage_class_specifier");
		parent.addChild(id);
		RESULT = parent;
	:}
	| STATIC:id {:
		System.err.println("Produccion 91");
		TreeNode parent = new TreeNode(null, "storage_class_specifier");
		parent.addChild(id);
		RESULT = parent;
	:}
	| AUTO:id {:
		System.err.println("Produccion 92");
		TreeNode parent = new TreeNode(null, "storage_class_specifier");
		parent.addChild(id);
		RESULT = parent;
	:}
	| REGISTER:id {:
		System.err.println("Produccion 93");
		TreeNode parent = new TreeNode(null, "storage_class_specifier");
		parent.addChild(id);
		RESULT = parent;
	:}
	;

type_specifier ::=
	VOID:type {:
		System.err.println("Produccion 94");
		TreeNode parent = new TreeNode(null, "type_specifier");
		parent.addChild(type);
		RESULT = parent;
	:}
	| CHAR:type {:
		System.err.println("Produccion 95");
		TreeNode parent = new TreeNode(null, "type_specifier");
		parent.addChild(type);
		RESULT = parent;
	:}
	| SHORT:type {:
		System.err.println("Produccion 96");
		TreeNode parent = new TreeNode(null, "type_specifier");
		parent.addChild(type);
		RESULT = parent;
	:}
	| INT:type {:
		System.err.println("Produccion 97");
		TreeNode parent = new TreeNode(null, "type_specifier");
		parent.addChild(type);
		RESULT = parent;
	:}
	| LONG:type {:
		System.err.println("Produccion 98");
		TreeNode parent = new TreeNode(null, "type_specifier");
		parent.addChild(type);
		RESULT = parent;
	:}
	| FLOAT:type {:
		System.err.println("Produccion 99");
		TreeNode parent = new TreeNode(null, "type_specifier");
		parent.addChild(type);
		RESULT = parent;
	:}
	| DOUBLE:type {:
		System.err.println("Produccion 100");
		TreeNode parent = new TreeNode(null, "type_specifier");
		parent.addChild(type);
		RESULT = parent;
	:}
	| SIGNED:type {:
		System.err.println("Produccion 101");
		TreeNode parent = new TreeNode(null, "type_specifier");
		parent.addChild(type);
		RESULT = parent;
	:}
	| UNSIGNED:type {:
		System.err.println("Produccion 102");
		TreeNode parent = new TreeNode(null, "type_specifier");
		parent.addChild(type);
		RESULT = parent;
	:}
	| struct_or_union_specifier:type {:
		System.err.println("Produccion 103");
		TreeNode parent = new TreeNode(null, "type_specifier");
		parent.addChild(type);
		RESULT = parent;
	:}
	| enum_specifier:type {:
		System.err.println("Produccion 104");
		TreeNode parent = new TreeNode(null, "type_specifier");
		parent.addChild(type);
		RESULT = parent;
	:}
	| TYPE_NAME:type {:
		System.err.println("Produccion 105");
		TreeNode parent = new TreeNode(null, "type_specifier");
		parent.addChild(type);
		RESULT = parent;
	:}
	;

struct_or_union_specifier ::=
	STRUCT:s IDENTIFIER:id CURLYL struct_declaration_list:sdl CURLYR {:
		System.err.println("Produccion 106");
		TreeNode parent = new TreeNode(null, "struct_or_union_specifier");
		parent.addChild(s);
		parent.addChild(id);
		parent.addChild(sdl);
		RESULT = parent;
	:}
	| STRUCT:s CURLYL struct_declaration_list:sdl CURLYR {:
		System.err.println("Produccion 107");
		TreeNode parent = new TreeNode(null, "struct_or_union_specifier");
		parent.addChild(s);
		parent.addChild(sdl);
		RESULT = parent;
	:}
	| STRUCT:s IDENTIFIER:id {:
		System.err.println("Produccion 108");
		TreeNode parent = new TreeNode(null, "struct_or_union_specifier");
		parent.addChild(s);
		parent.addChild(id);
		RESULT = parent;
	:}
	| UNION:u IDENTIFIER:id CURLYL struct_declaration_list:sdl CURLYR {:
		System.err.println("Produccion 109");
		TreeNode parent = new TreeNode(null, "struct_or_union_specifier");
		parent.addChild(u);
		parent.addChild(id);
		parent.addChild(sdl);
		RESULT = parent;
	:}
	| UNION:u CURLYL struct_declaration_list:sdl CURLYR {:
		System.err.println("Produccion 110");
		TreeNode parent = new TreeNode(null, "struct_or_union_specifier");
		parent.addChild(u);
		parent.addChild(sdl);
		RESULT = parent;
	:}
	| UNION:u IDENTIFIER:id {:
		System.err.println("Produccion 111");
		TreeNode parent = new TreeNode(null, "struct_or_union_specifier");
		parent.addChild(u);
		parent.addChild(id);
		RESULT = parent;
	:}
	;

struct_declaration_list ::=
	struct_declaration:s {:
		System.err.println("Produccion 112");
		TreeNode parent = new TreeNode(null, "struct_declaration_list");
		parent.addChild(s);
		RESULT = parent;
	:}
	| struct_declaration_list:sl struct_declaration:s {:
		System.err.println("Produccion 113");
		TreeNode parent = new TreeNode(null, "struct_declaration_list");
		parent.addChild(sl);
		parent.addChild(s);
		RESULT = parent;
	:}
	;

struct_declaration ::=
	specifier_qualifier_list:sq struct_declarator_list:sd SEMI {:
		System.err.println("Produccion 114");
		TreeNode parent = new TreeNode(null, "struct_declaration");
		parent.addChild(sq);
		parent.addChild(sd);
		RESULT = parent;
	:}
	;

specifier_qualifier_list ::=
	type_specifier:ts specifier_qualifier_list:sq {:
		System.err.println("Produccion 115");
		TreeNode parent = new TreeNode(null, "specifier_qualifier_list");
		parent.addChild(ts);
		parent.addChild(sq);
		RESULT = parent;
	:}
	| type_specifier:ts {:
		System.err.println("Produccion 116");
		TreeNode parent = new TreeNode(null, "specifier_qualifier_list");
		parent.addChild(ts);
		RESULT = parent;
	:}
	| type_qualifier:tq specifier_qualifier_list:sq {:
		System.err.println("Produccion 117");
		TreeNode parent = new TreeNode(null, "specifier_qualifier_list");
		parent.addChild(tq);
		parent.addChild(sq);
		RESULT = parent;
	:}
	| type_qualifier:tq {:
		System.err.println("Produccion 118");
		TreeNode parent = new TreeNode(null, "specifier_qualifier_list");
		parent.addChild(tq);
		RESULT = parent;
	:}
	;

struct_declarator_list ::=
	struct_declarator:s {:
		System.err.println("Produccion 119");
		TreeNode parent = new TreeNode(null, "struct_declarator_list");
		parent.addChild(s);
		RESULT = parent;
	:}
	| struct_declarator_list:sl COMMA struct_declarator:s {:
		System.err.println("Produccion 120");
		TreeNode parent = new TreeNode(null, "struct_declarator_list");
		parent.addChild(sl);
		parent.addChild(s);
		RESULT = parent;
	:}
	;

struct_declarator ::=
	declarator:d {:
		System.err.println("Produccion 121");
		TreeNode parent = new TreeNode(null, "struct_declarator");
		parent.addChild(d);
		RESULT = parent;
	:}
	| COLON constant_expression:ce {:
		System.err.println("Produccion 122");
		TreeNode parent = new TreeNode(null, "struct_declarator");
		parent.addChild(ce);
		RESULT = parent;
	:}
	| declarator:d COLON constant_expression:ce {:
		System.err.println("Produccion 123");
		TreeNode parent = new TreeNode(null, "struct_declarator");
		parent.addChild(d);
		parent.addChild(ce);
		RESULT = parent;
	:}
	;

enum_specifier ::=
	ENUM CURLYL enumerator_list:el CURLYR {:
		System.err.println("Produccion 124");
		TreeNode parent = new TreeNode(null, "enum_specifier");
		parent.addChild(el);
		RESULT = parent;
	:}
	| ENUM IDENTIFIER:id CURLYL enumerator_list:el CURLYR {:
		System.err.println("Produccion 125");
		TreeNode parent = new TreeNode(null, "enum_specifier");
		parent.addChild(id);
		parent.addChild(el);
		RESULT = parent;
	:}
	| ENUM IDENTIFIER:id {:
		System.err.println("Produccion 126");
		TreeNode parent = new TreeNode(null, "enum_specifier");
		parent.addChild(id);
		RESULT = parent;
	:}
	;

enumerator_list ::=
	enumerator:e {:
		System.err.println("Produccion 127");
		TreeNode parent = new TreeNode(null, "enumerator_list");
		parent.addChild(e);
		RESULT = parent;
	:}
	| enumerator_list:el COMMA enumerator:e {:
		System.err.println("Produccion 128");
		TreeNode parent = new TreeNode(null, "enumerator_list");
		parent.addChild(el);
		parent.addChild(e);
		RESULT = parent;
	:}
	;

enumerator ::=
	IDENTIFIER:id {:
		System.err.println("Produccion 129");
		TreeNode parent = new TreeNode(null, "enumerator");
		parent.addChild(id);
		RESULT = parent;
	:}
	| IDENTIFIER:id ASSIGN constant_expression:ce {:
		System.err.println("Produccion 130");
		TreeNode parent = new TreeNode(null, "enumerator");
		parent.addChild(id);
		parent.addChild(ce);
		RESULT = parent;
	:}
	;

type_qualifier ::=
	CONST:id {:
		System.err.println("Produccion 131");
		TreeNode parent = new TreeNode(null, "type_qualifier");
		parent.addChild(id);
		RESULT = parent;
	:}
	| VOLATILE:id {:
		System.err.println("Produccion 132");
		TreeNode parent = new TreeNode(null, "type_qualifier");
		parent.addChild(id);
		RESULT = parent;
	:}
	;

declarator ::=
	pointer:p direct_declarator:direct {:
		System.err.println("Produccion 133");
		TreeNode parent = new TreeNode(null, "declarator");
		parent.addChild(p);
		parent.addChild(direct);
		RESULT = parent;
	:}
	| direct_declarator:direct {:
		System.err.println("Produccion 134");
		TreeNode parent = new TreeNode(null, "declarator");
		parent.addChild(direct);
		RESULT = parent;
	:}
	;

direct_declarator ::=
	IDENTIFIER:identifier {:
		System.err.println("Produccion 135");
		TreeNode parent = new TreeNode(null, "direct_declarator");
		parent.addChild(identifier);
		RESULT = parent;
	:}
	| PARAL declarator:d PARAR {:
		System.err.println("Produccion 136");
		TreeNode parent = new TreeNode(null, "direct_declarator");
		parent.addChild(d);
		RESULT = parent;
	:}
	| direct_declarator:dd SQUAREDL constant_expression:ce SQUAREDR {:
		System.err.println("Produccion 137");
		TreeNode parent = new TreeNode(null, "direct_declarator");
		parent.addChild(new Symbol(-1,0,0,"array_declarator"));
		parent.addChild(dd);
		parent.addChild(ce);
		RESULT = parent;
	:}
	| direct_declarator:dd SQUAREDL SQUAREDR {:
		System.err.println("Produccion 138");
		TreeNode parent = new TreeNode(null, "direct_declarator");
		parent.addChild(new Symbol(-1,0,0,"array_declarator"));
		parent.addChild(dd);
		RESULT = parent;
	:}
	| direct_declarator:dd PARAL parameter_type_list:ptl PARAR {:
		System.err.println("Produccion 139");
		TreeNode parent = new TreeNode(null, "direct_declarator");
		parent.addChild(new Symbol(-1,0,0,"function_declarator"));
		parent.addChild(dd);
		parent.addChild(ptl);
		RESULT = parent;
	:}
	| direct_declarator:dd PARAL identifier_list:il PARAR {:
		System.err.println("Produccion 140");
		TreeNode parent = new TreeNode(null, "direct_declarator");
		parent.addChild(new Symbol(-1,0,0,"function_declarator"));
		parent.addChild(dd);
		parent.addChild(il);
		RESULT = parent;
	:}
	| direct_declarator:dd PARAL PARAR {:
		System.err.println("Produccion 141");
		TreeNode parent = new TreeNode(null, "direct_declarator");
		parent.addChild(new Symbol(-1,0,0,"function_declarator"));
		parent.addChild(dd);
		RESULT = parent;
	:}
	;

pointer ::=
	MUL:id {:
		System.err.println("Produccion 142");
		TreeNode parent = new TreeNode(null, "pointer");
		parent.addChild(id);
		RESULT = parent;
	:}
	| MUL:id type_qualifier_list:tql {:
		System.err.println("Produccion 143");
		TreeNode parent = new TreeNode(null, "pointer");
		parent.addChild(id);
		parent.addChild(tql);
		RESULT = parent;
	:}
	| MUL:id pointer:p {:
		System.err.println("Produccion 144");
		TreeNode parent = new TreeNode(null, "pointer");
		parent.addChild(id);
		parent.addChild(p);
		RESULT = parent;
	:}
	| MUL:id type_qualifier_list:tql pointer:p {:
		System.err.println("Produccion 145");
		TreeNode parent = new TreeNode(null, "pointer");
		parent.addChild(id);
		parent.addChild(tql);
		parent.addChild(p);
		RESULT = parent;
	:}
	;

type_qualifier_list ::=
	type_qualifier:tq {:
		System.err.println("Produccion 146");
		TreeNode parent = new TreeNode(null, "type_qualifier_list");
		parent.addChild(tq);
		RESULT = parent;
	:}
	| type_qualifier_list:tql type_qualifier:tq {:
		System.err.println("Produccion 147");
		TreeNode parent = new TreeNode(null, "type_qualifier_list");
		parent.addChild(tql);
		parent.addChild(tq);
		RESULT = parent;
	:}
	;


parameter_type_list ::=
	parameter_list:pl {:
		System.err.println("Produccion 148");
		TreeNode parent = new TreeNode(null, "parameter_type_list");
		parent.addChild(pl);
		RESULT = parent;
	:}
	| parameter_list:pl COMMA ELLIPSIS:id {:
		System.err.println("Produccion 149");
		TreeNode parent = new TreeNode(null, "parameter_type_list");
		parent.addChild(pl);
		parent.addChild(id);
		RESULT = parent;
	:}
	;

parameter_list ::=
	parameter_declaration:pd {:
		System.err.println("Produccion 150");
		TreeNode parent = new TreeNode(null, "parameter_list");
		parent.addChild(pd);
		RESULT = parent;
	:}
	| parameter_list:pl COMMA parameter_declaration:pd {:
		System.err.println("Produccion 151");
		TreeNode parent = new TreeNode(null, "parameter_list");
		parent.addChild(pl);
		parent.addChild(pd);
		RESULT = parent;
	:}
	;

parameter_declaration	::=
	declaration_specifiers:ds declarator:d {:
		System.err.println("Produccion 152");
		TreeNode parent = new TreeNode(null, "parameter_declaration");
		parent.addChild(ds);
		parent.addChild(d);
		RESULT = parent;
	:}
	| declaration_specifiers:ds abstract_declarator:ad {:
		System.err.println("Produccion 153");
		TreeNode parent = new TreeNode(null, "parameter_declaration");
		parent.addChild(ds);
		parent.addChild(ad);
		RESULT = parent;
	:}
	| declaration_specifiers:ds {:
		System.err.println("Produccion 154");
		TreeNode parent = new TreeNode(null, "parameter_declaration");
		parent.addChild(ds);
		RESULT = parent;
	:}
	;

identifier_list	::=
	IDENTIFIER:id {:
		System.err.println("Produccion 155");
		TreeNode parent = new TreeNode(null, "identifier_list");
		parent.addChild(id);
		RESULT = parent;
	:}
	| identifier_list:idl COMMA IDENTIFIER:id {:
		System.err.println("Produccion 156");
		TreeNode parent = new TreeNode(null, "identifier_list");
		parent.addChild(idl);
		parent.addChild(id);
		RESULT = parent;
	:}
	;

type_name	::=
	specifier_qualifier_list:sl {:
		System.err.println("Produccion 157");
		TreeNode parent = new TreeNode(null, "type_name");
		parent.addChild(sl);
		RESULT = parent;
	:}
	| specifier_qualifier_list:sl abstract_declarator:ad {:
		System.err.println("Produccion 158");
		TreeNode parent = new TreeNode(null, "type_name");
		parent.addChild(sl);
		parent.addChild(ad);
		RESULT = parent;
	:}
	;

abstract_declarator	::=
	pointer:p {:
		System.err.println("Produccion 159");
		TreeNode parent = new TreeNode(null, "abstract_declarator");
		parent.addChild(p);
		RESULT = parent;
	:}
	| direct_abstract_declarator:dad {:
		System.err.println("Produccion 160");
		TreeNode parent = new TreeNode(null, "abstract_declarator");
		parent.addChild(dad);
		RESULT = parent;
	:}
	| pointer:p direct_abstract_declarator:d {:
		System.err.println("Produccion 161");
		TreeNode parent = new TreeNode(null, "abstract_declarator");
		parent.addChild(p);
		parent.addChild(d);
		RESULT = parent;
	:}
	;

direct_abstract_declarator ::=
	PARAL:id abstract_declarator:ad PARAR:idr {:
		System.err.println("Produccion 162");
		TreeNode parent = new TreeNode(null, "direct_abstract_declarator");
		parent.addChild(ad);
		RESULT = parent;
	:}
	| SQUAREDL:id SQUAREDR:idr {:
		System.err.println("Produccion 163");
		TreeNode parent = new TreeNode(null, "direct_abstract_declarator");
		RESULT = parent;
	:}
	| SQUAREDL:id constant_expression:ce SQUAREDR:idr {:
		System.err.println("Produccion 164");
		TreeNode parent = new TreeNode(null, "direct_abstract_declarator");
		parent.addChild(ce);
		RESULT = parent;
	:}
	| direct_abstract_declarator:dad SQUAREDL:id SQUAREDR:idr {:
		System.err.println("Produccion 165");
		TreeNode parent = new TreeNode(null, "direct_abstract_declarator");
		parent.addChild(dad);
		RESULT = parent;
	:}
	| direct_abstract_declarator:dad SQUAREDL:id constant_expression:ce SQUAREDR:idr {:
		System.err.println("Produccion 166");
		TreeNode parent = new TreeNode(null, "direct_abstract_declarator");
		parent.addChild(dad);
		parent.addChild(ce);
		RESULT = parent;
	:}
	| PARAL:id PARAR:idr {:
		System.err.println("Produccion 167");
		TreeNode parent = new TreeNode(null, "direct_abstract_declarator");
		RESULT = parent;
	:}
	| PARAL:id parameter_type_list:ptl PARAR:idr {:
		System.err.println("Produccion 168");
		TreeNode parent = new TreeNode(null, "direct_abstract_declarator");
		parent.addChild(ptl);
		RESULT = parent;
	:}
	| direct_abstract_declarator:dad PARAL:id PARAR:idr {:
		System.err.println("Produccion 169");
		TreeNode parent = new TreeNode(null, "direct_abstract_declarator");
		parent.addChild(dad);
		RESULT = parent;
	:}
	| direct_abstract_declarator:dad PARAL:id parameter_type_list:ptl PARAR:idr {:
		System.err.println("Produccion 170");
		TreeNode parent = new TreeNode(null, "direct_abstract_declarator");
		parent.addChild(dad);
		parent.addChild(ptl);
		RESULT = parent;
	:}
	;

initializer ::=
	assignment_expression:ae {:
		System.err.println("Produccion 171");
		TreeNode parent = new TreeNode(null, "initializer");
		parent.addChild(ae);
		RESULT = parent;
	:}
	| CURLYL initializer_list:il CURLYR {:
		System.err.println("Produccion 172");
		TreeNode parent = new TreeNode(null, "initializer");
		parent.addChild(il);
		RESULT = parent;
	:}
	| CURLYL initializer_list:il COMMA CURLYR {:
		System.err.println("Produccion 173");
		TreeNode parent = new TreeNode(null, "initializer");
		parent.addChild(il);
		RESULT = parent;
	:}
	;

initializer_list ::=
	initializer:i {:
		System.err.println("Produccion 174");
		TreeNode parent = new TreeNode(null, "initializer");
		parent.addChild(i);
		RESULT = parent;
	:}
	| initializer_list:il COMMA initializer:i {:
		System.err.println("Produccion 175");
		TreeNode parent = new TreeNode(null, "initializer");
		parent.addChild(i);
		parent.addChild(il);
		RESULT = parent;
	:}
	;

statement ::=
	labeled_statement:otherstmnt {:
		System.err.println("Produccion 176");
		TreeNode parent = new TreeNode(null, "statement");
		parent.addChild(otherstmnt);
		RESULT = parent;
	:}
	| compound_statement:otherstmnt {:
		System.err.println("Produccion 177");
		TreeNode parent = new TreeNode(null, "statement");
		parent.addChild(otherstmnt);
		RESULT = parent;
	:}
	| expression_statement:otherstmnt {:
		System.err.println("Produccion 178");
		TreeNode parent = new TreeNode(null, "statement");
		parent.addChild(otherstmnt);
		RESULT = parent;
	:}
	| selection_statement:otherstmnt {:
		System.err.println("Produccion 179");
		TreeNode parent = new TreeNode(null, "statement");
		parent.addChild(otherstmnt);
		RESULT = parent;
	:}
	| iteration_statement:otherstmnt {:
		System.err.println("Produccion 180");
		TreeNode parent = new TreeNode(null, "statement");
		parent.addChild(otherstmnt);
		RESULT = parent;
	:}
	| jump_statement:otherstmnt {:
		System.err.println("Produccion 181");
		TreeNode parent = new TreeNode(null, "statement");
		parent.addChild(otherstmnt);
		RESULT = parent;
	:}
	;

labeled_statement ::=
	IDENTIFIER:id COLON statement:s {:
		System.err.println("Produccion 182");
		TreeNode parent = new TreeNode(null, "labeled_statement");
		parent.addChild(id);
		parent.addChild(s);
		RESULT = parent;
	:}
	| CASE:cs constant_expression:ce COLON statement:s {:
		System.err.println("Produccion 183");
		TreeNode parent = new TreeNode(null, "labeled_statement");
		parent.addChild(cs);
		parent.addChild(ce);
		parent.addChild(s);
		RESULT = parent;
	:}
	| DEFAULT:d COLON statement:s {:
		System.err.println("Produccion 184");
		TreeNode parent = new TreeNode(null, "labeled_statement");
		parent.addChild(d);
		parent.addChild(s);
		RESULT = parent;
	:}
	;

compound_statement ::=
	CURLYL CURLYR {:
		System.err.println("Produccion 185");
		TreeNode parent = new TreeNode(null, "compound_statement");
		RESULT = parent;
	:}
	| CURLYL decl_stmnt_list:dsl CURLYR {:
		System.err.println("Produccion 186");
		TreeNode parent = new TreeNode(null, "compound_statement");
		parent.addChild(dsl);
		RESULT = parent;
	:}
	;
declaration_list ::=
	declaration:d {:
		System.err.println("Produccion 187");
		TreeNode parent = new TreeNode(null, "declaration_list");
		parent.addChild(d);
		RESULT = parent;
	:}
	| declaration_list:dl declaration:d {:
		System.err.println("Produccion 188");
		TreeNode parent = new TreeNode(null, "declaration_list");
		parent.addChild(dl);
		parent.addChild(d);
		RESULT = parent;
	:}
	;

statement_list ::=
	statement:s {:
		System.err.println("Produccion 189");
		TreeNode parent = new TreeNode(null, "statement_list");
		parent.addChild(s);
		RESULT = parent;
	:}
	| statement_list:sl statement:s {:
		System.err.println("Produccion 190");
		TreeNode parent = new TreeNode(null, "statement_list");
		parent.addChild(sl);
		parent.addChild(s);
		RESULT = parent;
	:}
	;
decl_stmnt_list ::=
	declaration_list:dl {:
		System.err.println("Produccion 191");
		TreeNode parent = new TreeNode(null, "decl_stmnt_list");
		parent.addChild(dl);
		RESULT = parent;
	:}
	| statement_list:sl {:
		System.err.println("Produccion 191");
		TreeNode parent = new TreeNode(null, "decl_stmnt_list");
		parent.addChild(sl);
		RESULT = parent;
	:}
	| declaration_list:dl statement_list:sl {:
		System.err.println("Produccion 192");
		TreeNode parent = new TreeNode(null, "decl_stmnt_list");
		parent.addChild(dl);
		parent.addChild(sl);
		RESULT = parent;
	:}
	| statement_list:sl declaration_list:dl {:
		System.err.println("Produccion 193");
		TreeNode parent = new TreeNode(null, "decl_stmnt_list");
		parent.addChild(sl);
		parent.addChild(new Symbol(-1,0,0,"ERROR"));
		System.err.println("Las declaraciones se hacen antes");
		this.parser.errors.add("Las declaraciones se hacen antes");
		RESULT = parent;
	:}
	;

expression_statement ::=
	SEMI {:
		System.err.println("Produccion 194");
		TreeNode parent = new TreeNode(null, "expression_statement");
		RESULT = parent;
	:}
	| expression:e SEMI {:
		System.err.println("Produccion 195");
		TreeNode parent = new TreeNode(null, "expression_statement");
		parent.addChild(e);
		RESULT = parent;
	:}
	| expression:e declaration:d{:
		System.err.println("Produccion 196");
		TreeNode parent = new TreeNode(null, "expression_statement");
		parent.addChild(e);
		parent.addChild(new Symbol(-1,0,0,"ERROR"));
		RESULT = parent;
		System.err.println("Se esperaba ; no una declaración");
				this.parser.errors.add("Se esperaba ; no una declaración");

		//System.err.println(RESULT);
	:}
	| error SEMI {:
		System.err.println("Produccion 197");
		TreeNode parent = new TreeNode(null, "expression_statement");
		parent.addChild(new Symbol(-1,0,0,"ERROR"));
		RESULT = parent;
		System.err.println("Expresion malformada");
				this.parser.errors.add("Expresion malformada");

		//System.err.println(RESULT);
	:}
	;

selection_statement ::=
	IF:i PARAL expression:e PARAR statement:s {:
		System.err.println("Produccion 198");
		TreeNode parent = new TreeNode(null, "selection_statement");
		parent.addChild(i);
		parent.addChild(e);
		parent.addChild(s);
		RESULT = parent;
	:}
	| IF:i PARAL expression:e PARAR statement:s1 ELSE statement:s2 {:
		System.err.println("Produccion 199");
		TreeNode parent = new TreeNode(null, "selection_statement");
		parent.addChild(i);
		parent.addChild(e);
		parent.addChild(s1);
		parent.addChild(s2);
		RESULT = parent;
	:}
	| SWITCH:sw PARAL expression:e PARAR statement:s {:
		System.err.println("Produccion 200");
		TreeNode parent = new TreeNode(null, "selection_statement");
		parent.addChild(sw);
		parent.addChild(e);
		parent.addChild(s);
		RESULT = parent;
	:}
	;

iteration_statement ::=
	WHILE:wh PARAL expression:e PARAR statement:s {:
		System.err.println("Produccion 201");
		TreeNode parent = new TreeNode(null, "iteration_statement");
		parent.addChild(wh);
		parent.addChild(e);
		parent.addChild(s);
		RESULT = parent;
	:}
	| DO:d statement:s WHILE:wh PARAL expression:e PARAR SEMI {:
		System.err.println("Produccion 202");
		TreeNode parent = new TreeNode(null, "iteration_statement");
		parent.addChild(d);
		parent.addChild(s);
		parent.addChild(wh);
		parent.addChild(e);
		RESULT = parent;
	:}
	| FOR:f PARAL expression_statement:es1 expression_statement:es2 PARAR statement:s {:
		System.err.println("Produccion 203");
		TreeNode parent = new TreeNode(null, "iteration_statement");
		parent.addChild(f);
		parent.addChild(es1);
		parent.addChild(es2);
		parent.addChild(s);
		RESULT = parent;
	:}
	| FOR:f PARAL expression_statement:es1 expression_statement:es2 expression:e PARAR statement:s {:
		System.err.println("Produccion 204");
		TreeNode parent = new TreeNode(null, "iteration_statement");
		parent.addChild(f);
		parent.addChild(es1);
		parent.addChild(es2);
		parent.addChild(e);
		parent.addChild(s);
		RESULT = parent;
	:}
	;

jump_statement ::=
	GOTO:gt IDENTIFIER:id SEMI {:
		System.err.println("Produccion 205");
		TreeNode parent = new TreeNode(null, "jump_statement");
		parent.addChild(gt);
		parent.addChild(id);
		RESULT = parent;
	:}
	| CONTINUE:c SEMI {:
		System.err.println("Produccion 206");
		TreeNode parent = new TreeNode(null, "jump_statement");
		parent.addChild(c);
		RESULT = parent;
	:}
	| BREAK:br SEMI {:
		System.err.println("Produccion 207");
		TreeNode parent = new TreeNode(null, "jump_statement");
		parent.addChild(br);
		RESULT = parent;
	:}
	| RETURN:r SEMI {:
		System.err.println("Produccion 208");
		TreeNode parent = new TreeNode(null, "jump_statement");
		parent.addChild(r);
		RESULT = parent;
	:}
	| RETURN:r expression:e SEMI {:
		System.err.println("Produccion 209");
		TreeNode parent = new TreeNode(null, "jump_statement");
		parent.addChild(r);
		parent.addChild(e);
		RESULT = parent;
	:}
	;

translation_unit ::=
	external_declaration:ed {:
		System.err.println("Produccion 210");
		TreeNode parent = new TreeNode(null, "translation_unit");
		parent.addChild(ed);
		RESULT = parent;                
	:}
	| translation_unit:tu external_declaration:ed {:
		System.err.println("Produccion 211");
		TreeNode parent = new TreeNode(null, "translation_unit");
		parent.addChild(tu);
		parent.addChild(ed);
		RESULT = parent;
	:}
	;

external_declaration ::=
	function_definition:fd {:
		System.err.println("Produccion 214");
		TreeNode parent = new TreeNode(null, "external_declaration");
		parent.addChild(fd);
		RESULT = parent;
	:}
	| declaration:d {:
		System.err.println("Produccion 215");
		TreeNode parent = new TreeNode(null, "external_declaration");
		parent.addChild(d);
		RESULT = parent;
	:}
	| error {:
		System.err.println("Produccion 216");
		TreeNode parent = new TreeNode(null, "external_declaration");
		parent.addChild(new Symbol(-1,0,0,"ERROR"));
		RESULT = parent;
		System.err.println("No se esperaba token");
		this.parser.errors.add("No se esperaba token");
		//System.err.println(RESULT);
	:}
	;

function_definition ::=
	declaration_specifiers:ds declarator:d declaration_list:dl compound_statement:cs {:
		System.err.println("Produccion 217");
		TreeNode parent = new TreeNode(null, "function_definition");
		parent.addChild(ds);
		parent.addChild(d);
		parent.addChild(dl);
		parent.addChild(cs);
		RESULT = parent;
	:}
	| declaration_specifiers:ds declarator:d compound_statement:cs {:
		System.err.println("Produccion 218");
		TreeNode parent = new TreeNode(null, "function_definition");
		parent.addChild(ds);
		parent.addChild(d);
		parent.addChild(cs);
		RESULT = parent;
	:}
	| declarator:d declaration_list:dl compound_statement:cs {:
		System.err.println("Produccion 219");
		TreeNode parent = new TreeNode(null, "function_definition");
		parent.addChild(d);
		parent.addChild(dl);
		parent.addChild(cs);
		RESULT = parent;
	:}
	| declarator:d compound_statement:cs {:
		System.err.println("Produccion 220");
		TreeNode parent = new TreeNode(null, "function_definition");
		parent.addChild(d);
		parent.addChild(cs);
		RESULT = parent;
	:}
	;
