
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyectocompiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 8;
  public static final int SHORT = 19;
  public static final int SIGNED = 21;
  public static final int TIMES = 56;
  public static final int BOOL = 32;
  public static final int POINTER = 20;
  public static final int SCANF = 23;
  public static final int APOSTROPHE = 6;
  public static final int DIVIDEEQUALS = 63;
  public static final int PERIOD = 5;
  public static final int LESSEREQUALTHAN = 50;
  public static final int CLOSE_BRACKET = 38;
  public static final int GREATEREQUALTHAN = 52;
  public static final int TIMESEQUALS = 64;
  public static final int COMMA = 66;
  public static final int DOUBLE = 22;
  public static final int FALSE = 44;
  public static final int NOT = 46;
  public static final int DIFFERENT = 53;
  public static final int FLOAT = 16;
  public static final int NUM = 69;
  public static final int MINUSEQUALS = 62;
  public static final int CLOSE_BRACE = 40;
  public static final int OPEN_BRACKET = 37;
  public static final int GREATERTHAN = 51;
  public static final int MOD = 57;
  public static final int PRINTF = 24;
  public static final int TRUE = 43;
  public static final int LONG = 14;
  public static final int PLUS = 54;
  public static final int COMPARISSON = 48;
  public static final int QUOTE = 34;
  public static final int DIVIDE = 58;
  public static final int QUESTION = 67;
  public static final int WHILE = 27;
  public static final int EXCLAMATION = 2;
  public static final int LINE_COMMENT = 12;
  public static final int CHAR = 33;
  public static final int FOR = 28;
  public static final int VOID = 15;
  public static final int RETURN = 29;
  public static final int ELSE = 26;
  public static final int BREAK = 30;
  public static final int AMPERSAND = 3;
  public static final int INT = 31;
  public static final int NULL = 45;
  public static final int POINTERREFERENCE = 11;
  public static final int OPEN_PARENTHESIS = 35;
  public static final int EOF = 0;
  public static final int SEMICOLON = 65;
  public static final int COMMENT = 13;
  public static final int UNDERSCORE = 7;
  public static final int MAIN = 71;
  public static final int MINUS = 55;
  public static final int HAT = 10;
  public static final int OR = 42;
  public static final int error = 1;
  public static final int COMMENTARYSTART = 18;
  public static final int PLUSEQUALS = 61;
  public static final int LESSERTHAN = 49;
  public static final int IF = 25;
  public static final int UNSIGNED = 17;
  public static final int ID = 68;
  public static final int MINUSMINUS = 60;
  public static final int COLON = 4;
  public static final int OPEN_BRACE = 39;
  public static final int PLUSPLUS = 59;
  public static final int STRING = 70;
  public static final int AND = 41;
  public static final int CLOSE_PARENTHESIS = 36;
  public static final int EQUALS = 47;
  public static final int HASH = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EXCLAMATION",
  "AMPERSAND",
  "COLON",
  "PERIOD",
  "APOSTROPHE",
  "UNDERSCORE",
  "AT",
  "HASH",
  "HAT",
  "POINTERREFERENCE",
  "LINE_COMMENT",
  "COMMENT",
  "LONG",
  "VOID",
  "FLOAT",
  "UNSIGNED",
  "COMMENTARYSTART",
  "SHORT",
  "POINTER",
  "SIGNED",
  "DOUBLE",
  "SCANF",
  "PRINTF",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "RETURN",
  "BREAK",
  "INT",
  "BOOL",
  "CHAR",
  "QUOTE",
  "OPEN_PARENTHESIS",
  "CLOSE_PARENTHESIS",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "OPEN_BRACE",
  "CLOSE_BRACE",
  "AND",
  "OR",
  "TRUE",
  "FALSE",
  "NULL",
  "NOT",
  "EQUALS",
  "COMPARISSON",
  "LESSERTHAN",
  "LESSEREQUALTHAN",
  "GREATERTHAN",
  "GREATEREQUALTHAN",
  "DIFFERENT",
  "PLUS",
  "MINUS",
  "TIMES",
  "MOD",
  "DIVIDE",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUSEQUALS",
  "MINUSEQUALS",
  "DIVIDEEQUALS",
  "TIMESEQUALS",
  "SEMICOLON",
  "COMMA",
  "QUESTION",
  "ID",
  "NUM",
  "STRING",
  "MAIN"
  };
}

